<?xml version="1.0"?>
<package format="3">
    <name>ros_flexbuild</name>
    <version>1.0.0</version>
    <description>Header-only interface wrapper supporting both ROS 1 and ROS 2.</description>

    <maintainer email="celil@adastec.com">Celil Sincanli</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>std_msgs</depend>
    <depend>std_srvs</depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
    <build_type>ament_cmake</build_type>
    </export>
</package>